name: clinic_ops
version: "1.0.0"
config-version: 2

profile: clinic_ops

model-paths: ["models"]
test-paths: ["tests"]

models:
  clinic_ops:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
